"""empty message

Revision ID: 6f0a55d8a0c4
Revises: 
Create Date: 2023-09-12 18:18:28.379801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0a55d8a0c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_info',
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('place_name', sa.String(length=100), nullable=False),
    sa.Column('address_name', sa.String(length=100), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('place_url', sa.String(length=100), nullable=False),
    sa.Column('x', sa.String(length=256), nullable=False),
    sa.Column('y', sa.String(length=256), nullable=False),
    sa.Column('RESIDENCE_TIME_MIN', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_1', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_2', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_3', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_4', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_5', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_6', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_7', sa.String(length=256), nullable=False),
    sa.Column('VISIT_AREA_TYPE_CD_8', sa.String(length=256), nullable=False),
    sa.Column('REVISIT_INTENTION', sa.String(length=256), nullable=False),
    sa.Column('RCMDTN_INTENTION', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('item')
    )
    op.create_index(op.f('ix_item_info_item'), 'item_info', ['item'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_info_item'), table_name='item_info')
    op.drop_table('item_info')
    # ### end Alembic commands ###
