from pydantic import BaseModel
from typing import List

class New_User(BaseModel) :
    user: List[str]
    item: List[str]
    label: List[int]
    TRAVEL_MISSION_1: List[str]
    TRAVEL_MISSION_2: List[str]
    TRAVEL_MISSION_3: List[str]
    TRAVEL_MISSION_4: List[str]
    TRAVEL_MISSION_5: List[str]
    TRAVEL_MISSION_6: List[str] 
    TRAVEL_MISSION_7: List[str]
    TRAVEL_MISSION_8: List[str]
    TRAVEL_MISSION_9: List[str]
    TRAVEL_MISSION_10: List[str] 
    TRAVEL_MISSION_11: List[str] 
    TRAVEL_MISSION_12: List[str] 
    TRAVEL_MISSION_13: List[str] 
    TRAVEL_MISSION_14: List[str] 
    TRAVEL_MISSION_15: List[str] 
    TRAVEL_MISSION_16: List[str] 
    TRAVEL_MISSION_17: List[str] 
    TRAVEL_MISSION_18: List[str] 
    TRAVEL_MISSION_19: List[str] 
    TRAVEL_MISSION_20: List[str] 
    TRAVEL_MISSION_21: List[str] 
    GENDER: List[str] 
    AGE_GRP: List[str] 
    TRAVEL_STATUS_ACCOMPANY: List[str]
    TRAVEL_MOTIVE_1: List[str]
    TRAVEL_MOTIVE_2: List[str] 
    TRAVEL_MOTIVE_3: List[str] 
    TRAVEL_STYL_1: List[str] 
    TRAVEL_STYL_3: List[str]
    TRAVEL_STYL_6: List[str]
    RESIDENCE_TIME_MIN: List[str]
    REVISIT_INTENTION: List[str]
    RCMDTN_INTENTION: List[str]
    VISIT_AREA_TYPE_CD_1: List[str]
    VISIT_AREA_TYPE_CD_2: List[str]
    VISIT_AREA_TYPE_CD_3: List[str]
    VISIT_AREA_TYPE_CD_4: List[str] 
    VISIT_AREA_TYPE_CD_5: List[str] 
    VISIT_AREA_TYPE_CD_6: List[str] 
    VISIT_AREA_TYPE_CD_7: List[str] 
    VISIT_AREA_TYPE_CD_8: List[str]