"""empty message

Revision ID: 0defb9b0aab9
Revises: 
Create Date: 2023-09-19 03:01:26.354806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0defb9b0aab9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_features',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('new_spot_id', sa.String(length=256), nullable=True),
    sa.Column('spot_id', sa.String(length=256), nullable=True),
    sa.Column('VISIT_AREA_NM', sa.String(length=256), nullable=True),
    sa.Column('rename', sa.String(length=256), nullable=True),
    sa.Column('address_name', sa.String(length=256), nullable=True),
    sa.Column('category_name', sa.String(length=256), nullable=True),
    sa.Column('place_name', sa.String(length=256), nullable=True),
    sa.Column('place_url', sa.String(length=256), nullable=True),
    sa.Column('x', sa.String(length=256), nullable=True),
    sa.Column('y', sa.String(length=256), nullable=True),
    sa.Column('category_name_1', sa.String(length=256), nullable=True),
    sa.Column('category_name_2', sa.String(length=256), nullable=True),
    sa.Column('category_name_3', sa.String(length=256), nullable=True),
    sa.Column('category_name_4', sa.String(length=256), nullable=True),
    sa.Column('category_name_5', sa.String(length=256), nullable=True),
    sa.Column('RESIDENCE_TIME_MIN', sa.Float(), nullable=True),
    sa.Column('VISIT_CHC_REASON_가기_편해서_교통이_좋아서', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_가성비가_좋아서', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_과거_경험이_좋아서', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_교육성이_좋아서', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_기타', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_미디어_TV_정보_프로그램_등_평가가_좋아서', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_온라인_SNS_블로그_등_평가가_좋아서', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_지나가다_우연히', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_지명도_명소_핫플레이스', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_지인의_추천이_있어서', sa.Integer(), nullable=True),
    sa.Column('VISIT_CHC_REASON_편의시설_서비스가_좋아서', sa.Integer(), nullable=True),
    sa.Column('DGSTFN', sa.Float(), nullable=True),
    sa.Column('REVISIT_INTENTION', sa.Float(), nullable=True),
    sa.Column('RCMDTN_INTENTION', sa.Float(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_레저_스포츠_관련_시설_스키_카트_수상레저', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_문화_시설_공연장_영화관_전시관_등', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_산책로_둘레길_등', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_상업지구_거리_시장_쇼핑시설', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_역사_유적_종교_시설_문화재_박물관_촬영지_절_등', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_자연관광지', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_지역_축제_행사', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_체험_활동_관광지', sa.Integer(), nullable=True),
    sa.Column('VISIT_AREA_TYPE_CD_테마시설_놀이공원_워터파크', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_item_features_index'), 'item_features', ['index'], unique=False)
    op.create_index(op.f('ix_item_features_new_spot_id'), 'item_features', ['new_spot_id'], unique=False)
    op.create_table('ratings',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('TRAVEL_ID', sa.String(length=256), nullable=True),
    sa.Column('new_spot_id', sa.String(length=256), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['new_spot_id'], ['item_features.new_spot_id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_ratings_TRAVEL_ID'), 'ratings', ['TRAVEL_ID'], unique=False)
    op.create_index(op.f('ix_ratings_index'), 'ratings', ['index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_index'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_TRAVEL_ID'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_item_features_new_spot_id'), table_name='item_features')
    op.drop_index(op.f('ix_item_features_index'), table_name='item_features')
    op.drop_table('item_features')
    # ### end Alembic commands ###
